version: 2

multi-ecosystem-groups:
  all:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    multi-ecosystem-group: "all"
    patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "all"
    patterns: ["*"]

  - package-ecosystem: "pip"
    directory: "/"
    multi-ecosystem-group: "all"
    patterns: ["*"]
    ignore:
      # Dependabot should not update Home Assistant as that should match the homeassistant key in hacs.json
      - dependency-name: "homeassistant"
